routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth'])->group(function(){
    Route::get('/dashboard', function () {
        return view('layouts.app');
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('tests', 'TestsController');
Route::post('/tests/start', 'TestsController@startTest')->name('tests.startTest');

Route::resource('branches', 'BranchesController');
Route::delete('/trash/{branch}', 'BranchesController@trash')->name('branches.trash');

Route::resource('subjects', 'SubjectsController');
// Route::delete('/trash/{subject}', 'SubjectsController@trash')->name('subjects.trash');

Route::post('/test/result', 'AjaxController@getResult')->name('test.result');

Route::post('/ajax', 'AjaxController@getData');

app/Subject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Subject extends Model
{
    // use SoftDeletes;
    protected $fillable = [
        'name',
    ];

    public function semester(){
        return $this->belongsToMany(Semester::class, 'branch_semester_subject', 'subject_id', 'semester_id');
    }

    public function chapters()
    {
        return $this->belongsToMany(Chapter::class)->withTimestamps();
    }

    public function scopeSearch($query, $searchValue){
        if($searchValue){
            return $query->where('name', 'like', "%{$searchValue}%");
        }
        return $query;
    }

    public function scopeOrder($query, $orderBy){
        if($orderBy){
            $columns = ["sr_no", "name", "actions"];
            return $query->orderBy($columns[$orderBy[0]['column']], $orderBy[0]['dir']);
        }
        return $query;
    }

    public function scopeLimitBy($query, $start, $length){
        if($length != -1){
            return $query->offset($start)->limit($length);
        }
        return $query;
    }

    /**
     * METHODS FOR DATATABLE 
     */
    public static function getData($draw, $searchParameter, $orderBy, $start, $length){
        $filteredData = Subject::withoutTrashed()->search($searchParameter)->order($orderBy)->limitBy($start, $length)->get();
        $numberOfTotalRows = Subject::count();
        $numberOfFilteredRows = Subject::withoutTrashed()->search($searchParameter)->get()->count();
        $data = array();
        for($i = 0; $i < sizeof($filteredData); $i++)
        {
            $subarray = [];
            $subarray[] = $i + 1;
            $subarray[] = $filteredData[$i]->name;
            $subarray[] = <<<BUTTONS
            <button class='edit btn btn-warning btn-just-icon' data-id='{$filteredData[$i]->id}' data-toggle='modal' data-target='#editModal' onclick="displayEditModalForm('{$filteredData[$i]->id}')"><i class="nc-icon nc-ruler-pencil mr-1"></i> Edit</button>
            <button class='delete btn btn-danger btn-just-icon' data-id='{$filteredData[$i]->id}' data-toggle='modal' data-target='#deleteModal' onclick="displayDeleteModalForm('{$filteredData[$i]->id}')"><i class='nc-icon nc-box mr-1'></i> Delete</button>
BUTTONS;
            $data[] = $subarray;
        }

        $output = array(
            "draw"=>$draw,
            "recordsTotal"=>$numberOfTotalRows,
            "recordsFiltered"=>$numberOfFilteredRows,
            "data"=> $data
        );

        echo json_encode($output);
    }

}

app/Http/Controllers/SubjectsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateSubjectRequest;
use App\Http\Requests\UpdateSubjectRequest;
use App\Subject;
use Illuminate\Http\Request;

class SubjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(auth()->user()->isAdmin())
        {
            return view('subject.index');
        }
        abort(403);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('subject.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateSubjectRequest $request)
    {
        Subject::create([
            'name' => $request->name
        ]);

        session()->flash('success', 'Subject created successfully!');
        return redirect(route('branches.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function show(Subject $subject)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function edit(Subject $subject)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Subject $Subject
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateSubjectRequest $request, Subject $subject)
    {
        $subject->update([
            'name' => $request->name
        ]);
        session()->flash('success', 'Subject updated successfully!');
        return redirect(route('subjects.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function destroy(Subject $subject)
    {
        //
    }

    /**
     * Soft deletes the Subject
     * @param Subject $subject
     */
    public function trash(Subject $subject)
    {
        $subject->delete();
        session()->flash('success', 'Subject deleted successfully!');
        return redirect(route('branches.index'));
    }
}

resources/views/subject/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row mt-5">
        <div class="col-md-12">
            <div class="pull-right clearfix">
                <a href="{{ route('subjects.index') }}" class="btn btn-secondary m-1"><i
                        class="nc-icon nc-paper mr-1"></i> Manage Subject
                </a>
            </div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title">Create Subject</h4>
                </div>
                <div class="card-body">
                    <form action="{{ route('subjects.store') }}" method="POST">

                        @csrf
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label for="name" class="col-form-label text-md-right text-primary">{{ __('Subject Name') }}</label>

                                        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                        @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                </div>
                            </div>
                        </div>

                        <div class="pull-right clearfix">
                            <button type="submit" class="btn btn-primary m-1"><i
                                    class="nc-icon nc-check-2 mr-1"></i> Create
                            </button>
                        </div> 
    
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/subject/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12 mb-1">
            <div class="pull-right clearfix">
                <a href="{{ route('subjects.create') }}" class="btn btn-secondary m-1"><i
                        class="nc-icon nc-simple-add mr-1"></i> Create Subject
                </a>
            </div>
        </div>
        
        <div class="col-md-12 mt-3">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title">Subjects</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table" id="subject-datatable">
                            <thead class="text-primary">
                            <tr>
                                <th>
                                    #
                                </th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Actions
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--EDIT MODAL-->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Subject</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="#" method="POST" id="editForm">
                @csrf
                @method('PUT')
                <div class="modal-body">
                    <div class="form-group-row">
                        <input type="hidden" name="branch_id" id="branch_id">
                        <label for="name" class="col-sm-12">Subject Name</label>
                        <input type="text" class="form-control" id="name" name="name">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light m-1" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger m-1">Edit</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!--END EDITS MODAL-->

<!--DELETE MODAL-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Subject</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="" method="POST" id="deleteForm">
                @csrf
                @method('DELETE')
                <div class="modal-body">
                    <input type="hidden" name="record_id" id="record_id">
                    <p>Are you sure want to delete Subject??</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light m-1" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger m-1">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!--END DELETE MODAL-->
@endsection



@section('styles')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link href="{{ asset('assets/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
    <style>
        table{
            width: 100% !important;
        }
    </style>
@endsection

@section('scripts')
    <script src="{{ asset('assets/vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/js/page-level/subject/manage-subject.js') }}"></script>
    <script>
        function displayEditModalForm(branchID) {
            var url = '/subjects/' + branchID;
            $("#editForm").attr('action', url);
        }
        function displayDeleteModalForm(branchID) {
            var url = '/trash/' + branchID
            $("#deleteForm").attr('action', url);
        }
    </script>
@endsection