routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth'])->group(function(){
    Route::get('/dashboard', function () {
        return view('layouts.app');
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('tests', 'TestsController');
Route::post('/tests/start', 'TestsController@startTest')->name('tests.startTest');

Route::resource('branches', 'BranchesController');
Route::delete('/trash/{branch}', 'BranchesController@trash')->name('branches.trash');

Route::resource('subjects', 'SubjectsController');
// Route::delete('/trash/{subject}', 'SubjectsController@trash')->name('subjects.trash');

Route::post('/test/result', 'AjaxController@getResult')->name('test.result');

Route::post('/ajax', 'AjaxController@getData');

app/Branch.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Branch extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'name',
    ];

    /**
     * RELATIONSHIP METHODS
     */
    public function semesters(){
        return $this->belongsToMany(Semester::class, 'branch_semester_subject', 'semester_id', 'branch_id');
    }

    /**
     * SCOPE METHODS
     */

    public function scopeSearch($query, $searchValue){
        if($searchValue){
            return $query->where('name', 'like', "%{$searchValue}%");
        }
        return $query;
    }

    public function scopeOrder($query, $orderBy){
        if($orderBy){
            $columns = ["sr_no", "name", "actions"];
            return $query->orderBy($columns[$orderBy[0]['column']], $orderBy[0]['dir']);
        }
        return $query;
    }

    public function scopeLimitBy($query, $start, $length){
        if($length != -1){
            return $query->offset($start)->limit($length);
        }
        return $query;
    }


    /**
     * METHODS FOR DATATABLE 
     */
    public static function getData($draw, $searchParameter, $orderBy, $start, $length){
        $filteredData = Branch::withoutTrashed()->search($searchParameter)->order($orderBy)->limitBy($start, $length)->get();
        $numberOfTotalRows = Branch::count();
        $numberOfFilteredRows = Branch::withoutTrashed()->search($searchParameter)->get()->count();
        $data = array();
        for($i = 0; $i < sizeof($filteredData); $i++)
        {
            $subarray = [];
            $subarray[] = $i + 1;
            $subarray[] = $filteredData[$i]->name;
            $subarray[] = <<<BUTTONS
            <button class='edit btn btn-warning btn-just-icon' data-id='{$filteredData[$i]->id}' data-toggle='modal' data-target='#editModal' onclick="displayEditModalForm('{$filteredData[$i]->id}')"><i class="nc-icon nc-ruler-pencil mr-1"></i> Edit</button>
            <button class='delete btn btn-danger btn-just-icon' data-id='{$filteredData[$i]->id}' data-toggle='modal' data-target='#deleteModal' onclick="displayDeleteModalForm('{$filteredData[$i]->id}')"><i class='nc-icon nc-box mr-1'></i> Delete</button>
BUTTONS;
            $data[] = $subarray;
        }

        $output = array(
            "draw"=>$draw,
            "recordsTotal"=>$numberOfTotalRows,
            "recordsFiltered"=>$numberOfFilteredRows,
            "data"=> $data
        );

        echo json_encode($output);
    }


}

app/Http/Controllers/BranchesController.php
<?php

namespace App\Http\Controllers;

use App\Branch;
use App\Http\Requests\CreateBranchRequest;
use App\Http\Requests\UpdateBranchRequest;
use Illuminate\Http\Request;

class BranchesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(auth()->user()->isAdmin())
        {
            return view('branch.index');
        }
        abort(403);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('branch.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateBranchRequest $request)
    {
        Branch::create([
            'name' => $request->name
        ]);

        session()->flash('success', 'Branch created successfully!');
        return redirect(route('branches.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function show(Branch $branch)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function edit(Branch $branch)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBranchRequest $request, Branch $branch)
    {
        $branch->update([
            'name' => $request->name
        ]);
        session()->flash('success', 'Branch updated successfully!');
        return redirect(route('branches.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function destroy(Branch $branch)
    {
        //
    }

    /**
     * Soft deletes the Branch
     * @param Branch $branch
     */
    public function trash(Branch $branch)
    {
        $branch->delete();
        session()->flash('success', 'Branch deleted successfully!');
        return redirect(route('branches.index'));
    }
}

resources/views/branch/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row mt-5">
        <div class="col-md-12">
            <div class="pull-right clearfix">
                <a href="{{ route('branches.index') }}" class="btn btn-secondary m-1"><i
                        class="nc-icon nc-paper mr-1"></i> Manage Branch
                </a>
            </div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title">Create Branch</h4>
                </div>
                <div class="card-body">
                    <form action="{{ route('branches.store') }}" method="POST">

                        @csrf
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label for="name" class="col-form-label text-md-right text-primary">{{ __('Branch Name') }}</label>

                                        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                        @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                </div>
                            </div>
                        </div>

                        <div class="pull-right clearfix">
                            <button type="submit" class="btn btn-primary m-1"><i
                                    class="nc-icon nc-check-2 mr-1"></i> Create
                            </button>
                        </div> 
    
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/branch/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12 mb-1">
            <div class="pull-right clearfix">
                <a href="{{ route('branches.create') }}" class="btn btn-secondary m-1"><i
                        class="nc-icon nc-simple-add mr-1"></i> Create Branch
                </a>
            </div>
        </div>
        
        <div class="col-md-12 mt-3">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title">Branches</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table" id="branch-datatable">
                            <thead class="text-primary">
                            <tr>
                                <th>
                                    #
                                </th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Actions
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--EDIT MODAL-->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Branch</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="#" method="POST" id="editForm">
                @csrf
                @method('PUT')
                <div class="modal-body">
                    <div class="form-group-row">
                        <input type="hidden" name="branch_id" id="branch_id">
                        <label for="name" class="col-sm-12">Branch Name</label>
                        <input type="text" class="form-control" id="name" name="name">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light m-1" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger m-1">Edit</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!--END EDITS MODAL-->

<!--DELETE MODAL-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Branch</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="" method="POST" id="deleteForm">
                @csrf
                @method('DELETE')
                <div class="modal-body">
                    <input type="hidden" name="record_id" id="record_id">
                    <p>Are you sure want to delete Branch??</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light m-1" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger m-1">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!--END DELETE MODAL-->
@endsection



@section('styles')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link href="{{ asset('assets/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
    <style>
        table{
            width: 100% !important;
        }
    </style>
@endsection

@section('scripts')
    <script src="{{ asset('assets/vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/js/page-level/branch/manage-branch.js') }}"></script>
    <script>
        function displayEditModalForm(branchID) {
            var url = '/branches/' + branchID;
            $("#editForm").attr('action', url);
        }
        function displayDeleteModalForm(branchID) {
            var url = '/trash/' + branchID
            $("#deleteForm").attr('action', url);
        }
    </script>
@endsection