routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth'])->group(function(){
    Route::get('/dashboard', function () {
        return view('layouts.app');
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('tests', 'TestsController');
Route::post('/tests/start', 'TestsController@startTest')->name('tests.startTest');

Route::resource('branches', 'BranchesController');
Route::delete('/trash/{branch}', 'BranchesController@trash')->name('branches.trash');

Route::resource('subjects', 'SubjectsController');
// Route::delete('/trash/{subject}', 'SubjectsController@trash')->name('subjects.trash');

Route::post('/test/result', 'AjaxController@getResult')->name('test.result');

Route::post('/ajax', 'AjaxController@getData');

resources/views/layouts/pages/_footer.blade.php
<footer class="footer footer-black footer-own">
    <div class="container-fluid">
        <div class="row">
            <div class="credits m-auto">
                <span class="copyright">
                © <script>
                    document.write(new Date().getFullYear())
                </script> Quiz Mania
                </span>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/pages/_navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
    <div class="container-fluid">
        <div class="navbar-wrapper">
        <div class="navbar-toggle">
            <button type="button" class="navbar-toggler">
            <span class="navbar-toggler-bar bar1"></span>
            <span class="navbar-toggler-bar bar2"></span>
            <span class="navbar-toggler-bar bar3"></span>
            </button>
        </div>
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Quiz Mania') }}
        </a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-bar navbar-kebab"></span>
        <span class="navbar-toggler-bar navbar-kebab"></span>
        <span class="navbar-toggler-bar navbar-kebab"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <form>
                <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <div class="input-group-append">
                    <div class="input-group-text">
                    <i class="nc-icon nc-zoom-split"></i>
                    </div>
                </div>
                </div>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link btn-magnify" href="javascript:;">
                    <i class="nc-icon nc-layout-11"></i>
                    <p>
                    <span class="d-lg-none d-md-block">Stats</span>
                    </p>
                </a>
                </li>
                <li class="nav-item btn-rotate dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="nc-icon nc-bell-55"></i>
                    <p>
                    <span class="d-lg-none d-md-block">Some Actions</span>
                    </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="media align-items-center">
                            <span class="avatar avatar-sm rounded-circle">
                            <img alt="Image" src="{{ \Thomaswelton\LaravelGravatar\Facades\Gravatar::src(auth()->user()->email) }}" width="25" height="25">
                            </span>
                            <div class="media-body ml-2 d-none d-lg-block">
                            <span class="mb-0 text-sm  font-weight-bold">{{auth()->user()->first_name}}</span>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-menu  dropdown-menu-right ">
                        <div class="dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Welcome!</h6>
                        </div>
                        <a href="#" class="dropdown-item">
                            <i class="ni ni-single-02"></i>
                            <span>My profile</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                        document.getElementById('logout-form').submit();">
                            <i class="ni ni-user-run"></i>
                            <span>Logout</span>
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/pages/_sidebar.blade.php
<div class="sidebar" data-color="white" data-active-color="danger">
    <div class="logo">
    <a href="https://www.creative-tim.com" class="simple-text logo-mini">
        <div class="logo-image-small">
        <img src="../assets/img/logo-small.png">
        </div>
        <!-- <p>CT</p> -->
    </a>
    <a href="#" class="simple-text logo-normal">
        Quiz Mania
        <!-- <div class="logo-image-big">
            <img src="../assets/img/logo-big.png">
        </div> -->
    </a>
    </div>
    <div class="sidebar-wrapper pb-5">
    <ul class="nav">
        <li class="active ">
            <a href="{{ route('home') }}">
                <i class="nc-icon nc-bank"></i>
                <p>Dashboard</p>
            </a>
        </li>

        <li class="">
            <a href="{{ route('tests.index') }}">
                <i class="nc-icon nc-book-bookmark"></i>
                <p>Test</p>
            </a>
        </li>

        @if(@auth()->user()->isAdmin())

            <li class=" ">
                <a href="#">
                    <i class="nc-icon nc-circle-10"></i>
                    <p>Students</p>
                </a>
            </li>

            <li class=" ">
                <a href="{{ route('branches.index') }}">
                    <i class="nc-icon nc-hat-3"></i>
                    <p>Branches</p>
                </a>
            </li>

            <li class=" ">
            <a href="{{ route('subjects.index') }}">
                    <i class="nc-icon nc-paper"></i>
                    <p>Subjects</p>
                </a>
            </li>

            
            <li class=" ">
                <a href="#">
                    <i class="nc-icon nc-align-left-2"></i>
                    <p>Questions</p>
                </a>
            </li>
        @endif
        </ul>
    </div>
</div>